Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,8 +38,8 @@ jobs:
 
     - name: Check generated files
       run: |
-        cat config/v2rayn_nodes_base64.txt
-        cat config/clash_nodes.yaml
+        cat config/v2rayn_nodes_base64.txt || echo "V2rayN file not found or empty"
+        cat config/clash_nodes.yaml || echo "Clash file not found or empty"
 
     - name: Commit results
       run: |
